### ISSUE TITLE
Install from a swirl_courses fork

### ISSUE THREAD

**Issue by kdaily** [swirldev/swirl_courses#118]
Is it possible to install a specific lesson from a swirl_courses fork? I forked the repo, branched, and created two lessons. Can I use one of the built in functions to have some other users install to locally test?

**Comment by seankross** [comment]
You could try:
```
install_course_github("kdaily", "swirl_courses", branch = "synapsebasics", multi = TRUE)
```
Although this isn't a well-supported way of doing things. It may overwrite other courses you've installed. The way you have it set up now I would recommend downloading the zip file of the repository from the correct branch, then use:
```
install_course_zip("~/Desktop/swirl_courses-synapsebasics.zip", multi = TRUE, which_course = "Synapse")
```

**Comment by seankross** [comment]
Ideally you should make the course folder (`Synapse`) itself a git repository and then push that repository to GitHub. That way you could use:
```
install_course_github("kdaily", "Synapse")
```
in which case it would install cleanly.

**Comment by ncarchedi** [comment]
Alternatively, I think you can use install_course_github() with multi = TRUE to indicate that the course you want to install is not the only course in the repository.

**Comment by ncarchedi** [comment]
~~Alternatively, I think you can use `install_course_github()` with `multi = TRUE` to indicate that the course you want to install is not the only course in the repository.~~ Oops, didn't see @seankross's first comment.

**Comment by kdaily** [comment]
Thanks for the suggestions. I had it working with the zip file. I'll try
the other ways suggested and report back.

For development purposes why would I want to have a separate repo instead
of a fork? If I want a pull request later how would I get it into the
already offered lessons? Just wondering!

Thanks again.

**Comment by seankross** [comment]
That's a good question. Right now the `swirl_courses` repository only contains courses that are companions to the Data Science Specialization on Coursera.org. We're currently discussing a new structure where all Swirl courses are aggregated into one central repository, but this is still in development. Until then it's not likely that we'll be merging non-coursera material into `swirl_courses`. We don't want to be in charge of releasing new versions of everyone's Swirl courses. We would like it to be easy enough in the future to have a command like `install_from_swirl("Synapse")` and it would install your course from your personal repository, so that you could control new versions, etc, without the need to send us a pull request.

**Comment by kdaily** [comment]
OK thanks for the explanation, and it makes sense. It's easy enough to move
it over!

**Comment by seankross** [comment]
If you're interested in being notified when this feature is available you may be interested in subscribing to our [Google group](https://groups.google.com/forum/#!forum/swirl-discuss).

**Comment by kdaily** [comment]
Will do @seankross. Thanks for the feedback, all.
