### ISSUE TITLE
AM not able to successfully send noification after completing a swirl lesson for R course. 

### ISSUE THREAD

**Issue by SamiBoy2001** [swirldev/swirl_courses#209]

**Comment by seankross** [comment]
What happens when you try to send notification?

**Comment by sombodyg** [comment]
I am also not able to send files automatically .....
#############################################################
| Is the following information correct?

Course ID: rprog-032
Submission login (email): email Here
Submission password: VrFSgBhq9n

1: Yes, go ahead!
2: No, I need to change something.

Selection: 1

| I'll try to tell Coursera you've completed this lesson now.

| Exception: We could not verify your username / password, please try again. (Note that
| your password is case-sensitive.)

| I'm sorry, something went wrong with automatic submission.

| Would you like to retry automatic submission or just submit manually?

1: Retry automatic submission
2: Submit manually

Selection: 1

| Is the following information correct?

Course ID: rprog-032
Submission login (email): email
Submission password: VrFSgBhq9n

1: Yes, go ahead!
2: No, I need to change something.

Selection: 1
#############################################################

**Comment by seankross** [comment]
@sombodyg try this guide: https://github.com/swirldev/swirl/wiki/Coursera-FAQ#automatic-submission-failed-how-do-i-submit-manually and let me know if that works.

**Comment by sombodyg** [comment]
Thanks Sean,

I was able to submit manually but just gave you and example to check if there is a problem in submitting automatically .
Thanks much for the reply :)

**Comment by seankross** [comment]
No problem, glad you were bale to submit. Let mw know if you have any other issues.

**Comment by dongyidongyi** [comment]
Hi Sean, 

This is Yi, I have encountered the same problem while submitting my assignment through swirl, by reading your replies and the link you mentioned, I realized that it is probably because I have a date swirl version, however, I am not able to figure out how to update the old swirl version in my laptop

the old version, I downloaded by using:

**install_from_swirl("Regression Models", dev = FALSE, mirror = "bitbucket")**

since what indicated in the coursera's example doesn't work for me...and I checked in R help getting the previous line as a substitution for install the course...

**install_from_swirl("Regression Models")**

Error message I got
**Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer**

**Comment by seankross** [comment]
@dongyidongyi see https://github.com/swirldev/swirl/issues/387#issuecomment-170266258 and let me know if that works.

**Comment by dongyidongyi** [comment]
Thank you Sean! It works. And another working around is using VPN. I am a
user from mainland of China, with out the VPN, I can not download those
courses, but once VPN starts to work, I am able to download those... I
guess there is some firewall setup for whatever the server of those package
is...or maybe the mirror I am using(France one)...

Best

Yi

2016-03-09 4:20 GMT+08:00 Sean Kross <notifications@github.com>:

> @dongyidongyi <https://github.com/dongyidongyi> see swirldev/swirl#387
> (comment)
> <https://github.com/swirldev/swirl/issues/387#issuecomment-170266258> and
> let me know if that works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swirldev/swirl_courses/issues/209#issuecomment-193951525>
> .
>



-- 
DONG Yi
Shanghai
China

Mobile: +86-14782351181
